spring.application.name=domus

jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/domus
spring.datasource.username=postgres
#spring.datasource.password=postgres
spring.datasource.password=GT!l1nux
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#logging.level.org.springframework=DEBUG